name: build and release
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Assemble release with gradle
        run: ./gradlew assembleRelease
        working-directory: ./android
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release artifact
          path: android/app/build/outputs/apk/release/app-release.apk
